name: Add new tests to PR

on:
  pull_request:

jobs:
  test-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Extract tests from origin branch
        run: |
          yarn extract origin_tests.txt"
        env:
          CI: true

      - name: Extract tests from destination branch
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          yarn install
          yarn extract destination_tests.txt
        env:
          CI: true

      - name: Compare tests
        run: |
          DIFF=$(diff origin_tests.txt destination_tests.txt)
          echo "$DIFF" > tests_diff.txt

      - name: Comment on pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Tests Difference:**

            ```
            $(cat tests_diff.txt)
            ```

      - name: Cleanup
        run: |
          rm origin_tests.txt destination_tests.txt tests_diff.txt
