name: Add new tests to PR

on:
  pull_request:

jobs:
  test-pr:
    name: Get test difference
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.results.outputs.has_changes }}
      tests_before: ${{ steps.results.outputs.tests_before }}
      tests_after: ${{ steps.results.outputs.tests_after }}
      diff: ${{ steps.results.outputs.diff }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          yarn --frozen-lockfile

      - name: Get target tests
        id: target-branch
        run: |
          TESTS=$(yarn -s test:ls 2>/dev/null)
          TESTS="${TESTS//'%'/'%25'}"
          TESTS="${TESTS//$'\n'/'%0A'}"
          TESTS="${TESTS//$'\r'/'%0D'}"
          echo "tests_before=${TESTS}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          yarn --frozen-lockfile

      - name: Get current branch tests
        id: current-branch
        run: |
          TESTS=$(yarn -s test:ls 2>/dev/null)
          TESTS="${TESTS//'%'/'%25'}"
          TESTS="${TESTS//$'\n'/'%0A'}"
          TESTS="${TESTS//$'\r'/'%0D'}"
          echo "tests_after=${TESTS}" >> $GITHUB_OUTPUT

      - name: Get diff
        id: test-diff
        run: |
          OR="${{ steps.current-branch.outputs.tests_before }}"
          BR="${{ steps.current-branch.outputs.tests_after }}"

          OR="${OR//'%25'/'%'}"
          OR="${OR//'%0A'/$'\n'}"
          OR="${OR//'%0D'/$'\r'}"
          BR="${BR//'%25'/'%'}"
          BR="${BR//'%0A'/$'\n'}"
          BR="${BR//'%0D'/$'\r'}"
          echo "$OR" > origin.txt
          echo "$BR" > branch.txt

          DIFF=$(diff origin.txt branch.txt)
          if [ ! -z "$DIFF" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "diff=${DIFF}" >> $GITHUB_OUTPUT

  comment-pr:
    runs-on: ubuntu-latest
    needs: [test-pr]
    if: needs.test-per.outputs.has_changes == 'true'
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Modifiche ai test
            ${{ needs.test-pr.outputs.diff }}
          comment_tag: test-diff
