name: Add new tests to PR

on:
  pull_request:

jobs:
  test-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          yarn --frozen-lockfile

      - name: Extract tests from origin branch
        run: |
          yarn extract tests.txt
          cat tests.txt | sort > origin_tests.txt
          rm tests.txt
        env:
          CI: true

      - name: Extract tests from destination branch
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
          yarn --frozen-lockfile
          yarn extract tests.txt
          cat tests.txt | sort > destination_tests.txt
          rm tests.txt
        env:
          CI: true

      - name: Compare tests
        run: |
          diff origin_tests.txt destination_tests.txt > tests_diff.txt || true

      - name: Read file content and set as environment variable
        id: read-file
        run: |
          echo "::set-output name=content::$(cat tests_diff.txt)"

      - name: Comment on pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Tests Difference:**

            ```
            ${{ steps.read-file.outputs.content }}
            ```

      - name: Cleanup
        run: |
          rm origin_tests.txt destination_tests.txt tests_diff.txt
